name: Build and test cunumeric on GH

concurrency:
  group: ci-build-and-test-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - "pull-request/[0-9]+"
      - "branch-*"

jobs:
  filter-by-triggering-event:
    name: Filter by triggering event
    uses: ./.github/workflows/filter-by-triggering-event.yml

  build-and-test:
    needs: filter-by-triggering-event
    if: needs.filter-by-triggering-event.outputs.ok == 'true'
    strategy:
      fail-fast: false
      matrix:
        include:
          - {build-target: cpu}
          - {build-target: gpu}
    uses:
      ./.github/workflows/gh-build-and-test.yml
    with:
      build-target: ${{ matrix.build-target }}
      sha: ${{ github.sha }}
