name: Clean up

on:
  workflow_call:
    inputs:
      build-target:
        required: true
        type: string
      sha:
        required: true
        type: string

env:
  IMAGE_NAME: cunumeric-${{ inputs.build-target }}

jobs:
  cleanup:
    permissions:
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Delete docker image
        run: |
          set -xeuo pipefail

          PACKAGE_VERSION_ID=$(
            GH_TOKEN=${{ github.token }} gh api \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -H "Accept: application/vnd.github+json" \
              --jq '.[] | select(.metadata.container.tags[] == "${{ inputs.sha }}") | .id' \
              /users/${{ github.repository_owner }}/packages/container/$IMAGE_NAME/versions \
            || echo "";
          )

          if test -n "$PACKAGE_VERSION_ID"; then
            GH_TOKEN=${{ github.token }} gh api \
              --method DELETE \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -H "Accept: application/vnd.github+json" \
              /users/${{ github.repository_owner }}/packages/container/$IMAGE_NAME/versions/$PACKAGE_VERSION_ID \
            || true;
          fi
